dbs-leipzig/gradoop

gradoop-flink/src/main/java/org/gradoop/model/api/functions/BinaryFunction.java, gradoop-flink/src/main/java/org/gradoop/model/api/functions/ProjectionFunction.java, gradoop-flink/src/main/java/org/gradoop/model/api/operators/BinaryCollectionToCollectionOperator.java, gradoop-flink/src/main/java/org/gradoop/model/api/operators/BinaryCollectionToValueOperator.java, gradoop-flink/src/main/java/org/gradoop/model/impl/functions/tuple/Value1Of2.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/projection/Projection.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/projection/functions/EdgeSourceUpdateJoin.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/projection/functions/EdgeTargetUpdateJoin.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/projection/functions/ProjectionEdgeMapper.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/projection/functions/ProjectionVertexMapper.java, gradoop-flink/src/test/java/org/gradoop/model/impl/operators/projection/ProjectionTest.java
* Added interface `BinaryFunction` which is implemented by `ProjectionFunction`
* Changed ProjectionTest accordingly.
=> Projection creates new elements instead of modifying existing, fixes #134

gradoop-flink/src/test/java/org/gradoop/model/impl/operators/split/SplitTest.java
Added test for result with only one graph. Renamed TestHelperFunction to SelectKeyValues.
=> Refactored SpĺitTest. Fixes #178.

gradoop-flink/src/main/java/org/gradoop/model/impl/functions/graphcontainment/PairVertexWithGraphs.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/base/BinaryCollectionToCollectionOperatorBase.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/base/SetOperatorBase.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/base/functions/LeftJoin0OfTuple2.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/base/functions/package-info.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/difference/Difference.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/difference/functions/CreateTuple2WithLong.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/difference/functions/IdOf0InTuple2.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/difference/functions/RemoveCut.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/difference/functions/package-info.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/intersection/Intersection.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/intersection/functions/GroupCountEquals.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/intersection/functions/package-info.java
Created multiple new classes for former inner and anonymous classes in the BinaryCollectionToCollectionOperatorBase, the SetOperatorBase and instances of BinaryCollectionToCollectionOperator (Difference, Intersection).
=> Encapsulated inner and anonymous function classes. Fixes #149.

gradoop-core/src/main/java/org/gradoop/model/impl/properties/PropertyValue.java, gradoop-core/src/test/java/org/gradoop/model/impl/properties/PropertyValueTest.java
* extended unit tests for ordinal, null and boolean types
=> Decoding PropertyValue before comparison, fixes #210

gradoop-checkstyle/src/main/resources/gradoop/checkstyle.xml
* set line separator to unix style ("lf")
=> Set lineSeparator for NewlineAtEndOfFile, fixes #205

gradoop-datagen/pom.xml, gradoop-examples/pom.xml, gradoop-examples/src/main/java/org/gradoop/examples/io/EdgeListExample.java, gradoop-examples/src/main/java/org/gradoop/examples/io/package-info.java, gradoop-flink/src/main/java/org/gradoop/io/impl/graph/functions/InitEPGMEdge.java, gradoop-flink/src/main/java/org/gradoop/io/impl/graph/tuples/ImportEdge.java, gradoop-flink/src/main/java/org/gradoop/io/impl/graph/tuples/ImportVertex.java
* overloaded constructors for ImportEdge/-Vertex
* renamed fields in ImportEdge (sourceVertexId -> sourceId)
=> add EdgeList example for I/O, fixes #260

gradoop-flink/src/main/java/org/gradoop/model/impl/functions/epgm/GraphElementsHeadsToTransaction.java, gradoop-flink/src/test/java/org/gradoop/model/impl/GraphTransactionTest.java
=> #273 null pointer in to transaction

dev-support/benchmark/grouping/grouping.conf, dev-support/benchmark/grouping/grouping.sh, gradoop-benchmark/src/main/java/org/gradoop/benchmark/grouping/GroupingBenchmark.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/Grouping.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/GroupingGroupCombine.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/GroupingGroupReduce.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/BuildBase.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/BuildSuperVertex.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/BuildVertexGroupItem.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/BuildVertexWithSuperVertex.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/BuildVertexWithSuperVertexBC.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/CombineVertexGroupItems.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/FilterRegularVertices.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/FilterSuperVertices.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/ReduceEdgeGroupItems.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/ReduceVertexGroupItemBase.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/ReduceVertexGroupItems.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/TransposeVertexGroupItems.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/UpdateEdgeGroupItem.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/aggregation/package-info.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/package-info.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/tuples/VertexGroupItem.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/tuples/VertexWithSuperVertex.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/tuples/package-info.java, gradoop-flink/src/main/java/org/gradoop/model/impl/tuples/IdWithIdSet.java, gradoop-flink/src/test/java/org/gradoop/model/impl/operators/grouping/GroupingGroupCombineTest.java
* added groupCombine strategy using broadcasting for vertex updates
* updated benchmark accordingly
=> #283 grouping improvement

gradoop-examples/src/main/java/org/gradoop/examples/biiig/CategoryCharacteristicPatterns.java, gradoop-examples/src/main/java/org/gradoop/examples/sna/SNABenchmark2.java, gradoop-flink/src/main/java/org/gradoop/model/api/functions/ApplyAggregateFunction.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/aggregation/ApplyAggregation.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/aggregation/functions/AggregateWithDefaultValueFunction.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/aggregation/functions/count/EdgeCount.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/aggregation/functions/count/VertexCount.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/aggregation/functions/max/Max.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/aggregation/functions/max/MaxEdgeProperty.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/aggregation/functions/max/MaxOfPropertyValues.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/aggregation/functions/max/MaxOfPropertyValuesGroups.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/aggregation/functions/max/MaxVertexProperty.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/aggregation/functions/min/Min.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/aggregation/functions/min/MinEdgeProperty.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/aggregation/functions/min/MinOfPropertyValues.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/aggregation/functions/min/MinOfPropertyValuesGroups.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/aggregation/functions/min/MinVertexProperty.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/aggregation/functions/sum/Sum.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/aggregation/functions/sum/SumEdgeProperty.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/aggregation/functions/sum/SumPropertyValues.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/aggregation/functions/sum/SumPropertyValuesGroups.java, gradoop-flink/src/main/java/org/gradoop/model/impl/operators/aggregation/functions/sum/SumVertexProperty.java, gradoop-flink/src/test/java/org/gradoop/model/impl/operators/aggregation/AggregationTest.java
Added AggregateWithDefaultFunction to make it possible to add a user defined default value to AggregationFunctions and ApplyAggregationFunctions.
Adjusted tests and examples accordingly.
Fixes #231.
=> Removed need to specify default value for each aggregation.

gradoop-flink/src/test/java/org/gradoop/flink/io/impl/graph/GraphIOTest.java
* testing GraphDataSource without label and/or properties -> no NPE
* fixes #334
=> [#334] added test cases for GraphDataSource

gradoop-flink/src/main/java/org/gradoop/flink/io/impl/tlf/functions/TLFFileFormat.java
Changed from string concatenation with '+' to StringBuilder approach.
=> Changed to StringBuilder concatenation. Fixes #302

README.md, pom.xml
* added recent publication / talks
* added @Venom590 as developer in pom
=> documentation updates

pom.xml
=> [#345] setup maven release plugin

gradoop-examples/pom.xml, pom.xml
=> [#347] removed gradoop-algorithms dependency

gradoop-examples/src/main/java/org/gradoop/examples/simulation/PatternMatchingRunner.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/LogicalGraph.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/preserving/explorative/DistributedTraverser.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/preserving/explorative/ExplorativePatternMatching.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/preserving/explorative/debug/PrintEdgeStep.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/preserving/explorative/debug/PrintEmbeddingWithTiePoint.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/preserving/explorative/debug/PrintVertexStep.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/preserving/explorative/debug/package-info.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/preserving/explorative/functions/BuildEdgeStep.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/preserving/explorative/functions/BuildEmbeddingWithTiePoint.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/preserving/explorative/functions/BuildVertexStep.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/preserving/explorative/functions/EdgeHasCandidate.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/preserving/explorative/functions/UpdateEdgeMappings.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/preserving/explorative/functions/UpdateVertexMappings.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/preserving/explorative/functions/VertexHasCandidate.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/preserving/explorative/functions/package-info.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/preserving/explorative/package-info.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/preserving/explorative/tuples/EdgeStep.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/preserving/explorative/tuples/EmbeddingWithTiePoint.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/preserving/explorative/tuples/VertexStep.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/preserving/explorative/tuples/package-info.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/preserving/package-info.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/isomorphism/explorative/ExplorativePatternMatchingTest.java
* renamed package from isomorphism to preserving
* renamed operators to ExplorativePatternMatching
* updated package infos
* fixes #349
=> [#349] rename ExplorativeSubgraphIsomorphism

gradoop-checkstyle/src/main/resources/gradoop/checkstyle.xml, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/overlap/Overlap.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/overlap/OverlapBase.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/overlap/ReduceOverlap.java, pom.xml
* using 2.16 (checkstyle 6.2)
* set lineBreakIndentation to 0
* fixes #355
=> [#355] updated maven-checkstyle plugin

gradoop-common/src/main/java/org/gradoop/common/model/impl/properties/PropertyList.java, gradoop-common/src/test/java/org/gradoop/common/model/impl/properties/PropertyListTest.java
Added the two methods `remove(Property property)` and `remove(String key)` to be able to remove  a property from PropertyList.
=> Added methods to remove a property from PropertyList.

gradoop-examples/pom.xml, gradoop-examples/src/main/java/org/gradoop/benchmark/patternmatching/TraverserBenchmark.java, gradoop-examples/src/main/java/org/gradoop/examples/AbstractRunner.java
* run fixed and dynamic queries
* expects prepared graph files (vertex ids, edge triples)
* fixes #382
=> [#382] updated traverser benchmark

dev-support/gradoop-idea-codestyle.xml, gradoop-checkstyle/src/main/resources/gradoop/checkstyle.xml
=> [#111] set maximum line width to 100

gradoop-examples/src/main/java/org/gradoop/benchmark/patternmatching/Queries.java
=> [#387] updated traverser benchmark

gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/embeddings/Embedding.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/embeddings/EmbeddingEntry.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/embeddings/IdEntry.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/embeddings/ListEntry.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/embeddings/ProjectionEntry.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/embeddings/package-info.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/physical/CartesianProduct.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/physical/Expand.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/physical/ExpandOne.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/physical/FilterAndProjectEdges.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/physical/FilterAndProjectEmbeddings.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/physical/FilterAndProjectVertices.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/physical/FilterEdges.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/physical/FilterEmbeddings.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/physical/FilterVertices.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/physical/JoinEmbeddings.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/physical/PhysicalOperator.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/physical/ProjectEdges.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/physical/ProjectEmbeddings.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/physical/ProjectVertices.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/physical/ValueJoin.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/physical/package-info.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/utils/ExpandDirection.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/utils/package-info.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/physical/OperatorIntegrationTest.java
Fixes #381 
Adds skeleton classes for physical operators
=> #381 Add API for physical operators and embeddings

gradoop-flink/src/main/java/org/gradoop/flink/datagen/transactions/predictable/PredictableTransactionsGenerator.java, gradoop-flink/src/main/java/org/gradoop/flink/io/impl/tlf/TLFDataSource.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/GraphCollection.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/functions/epgm/GraphElementExpander.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/functions/epgm/GraphTransactionTriple.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/functions/epgm/GraphVerticesEdges.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/functions/epgm/PairElementWithNewId.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/functions/epgm/TransactionEdges.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/functions/epgm/TransactionFromSets.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/functions/epgm/TransactionGraphHead.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/functions/epgm/TransactionVertices.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/functions/utils/First.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/tuples/GraphTransaction.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/GraphTransactionTest.java
* replaced full outer join with groupBy and left outer join
* using combiner for group by step
* refactored some convenience UDFs (added field forwarding annotations, reuse tuples, etc.)
* removed type method from GraphTransaction
* fixes #391
=> [#391] improved transaction conversion

gradoop-examples/src/main/java/org/gradoop/benchmark/patternmatching/Queries.java, gradoop-examples/src/main/java/org/gradoop/benchmark/patternmatching/TraverserBenchmark.java
* added two more queries
* fixes #395
=> [#395] update traverser benchmark

gradoop-common/src/main/java/org/gradoop/common/model/impl/id/GradoopId.java, gradoop-common/src/main/java/org/gradoop/common/model/impl/properties/PropertyValue.java, gradoop-common/src/test/java/org/gradoop/common/GradoopTestUtils.java, gradoop-common/src/test/java/org/gradoop/common/model/impl/id/GradoopIdTest.java, gradoop-common/src/test/java/org/gradoop/common/model/impl/properties/PropertyValueTest.java
Fixes #400 
Adds `GradoopId` to the supported `PropertyValue`s
=> #400 Add GradoopId to supported property values

gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/transactional/function/InitGraphHeadWithLineage.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/transactional/TransactionalPatternMatchingTest.java
* storing lineage as GradoopId
* fixes #404
=> [#404] Updated TransactionalPatternMatching

gradoop-flink/src/main/java/org/gradoop/flink/io/impl/tlf/TLFDataSink.java, gradoop-flink/src/main/java/org/gradoop/flink/io/impl/tlf/functions/EdgeLabelList.java, gradoop-flink/src/main/java/org/gradoop/flink/io/impl/tlf/functions/TLFDictionaryMapGroupReducer.java, gradoop-flink/src/main/java/org/gradoop/flink/io/impl/tlf/functions/VertexLabelList.java
Changed from using lists of strings(labels) to a dataset of strings only and removed duplicates to minimize group reduction and improve dictionary generation.
=> [#379]Updated dictionary generation.

gradoop-common/src/main/java/org/gradoop/common/model/impl/comparators/EPGMIdentifiableComparator.java, gradoop-common/src/main/java/org/gradoop/common/model/impl/comparators/package-info.java, gradoop-common/src/test/java/org/gradoop/common/GradoopTestUtils.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/GradoopFlinkTestUtils.java
* extracted id based comparator
* removed DRY violations
* fixes #422
=> [#422] refactored TestUtils

gradoop-flink/src/main/java/org/gradoop/flink/model/impl/functions/epgm/ByProperty.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/functions/epgm/Label.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/functions/epgm/Property.java
Added filter function to epgm function `Label` and created filter function on properties from epgm elements.
=> #428 Add filter function for label and property

gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/project/functions/ProjectEdge.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/project/ProjectEdgesTest.java
fixes #435
Return the correct edege embedding for empty property name list
=> #435 Fix ProjectEdges operator for empty property names list

gradoop-examples/src/main/java/org/gradoop/examples/io/JSONExample.java, gradoop-examples/src/main/java/org/gradoop/examples/sna/SNABenchmark1.java, gradoop-flink/src/main/java/org/gradoop/flink/model/api/operators/LogicalGraphOperators.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/LogicalGraph.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/Grouping.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/GroupingGroupCombine.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/GroupingGroupReduce.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/functions/BuildEdgeGroupItem.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/functions/BuildSuperVertex.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/functions/BuildVertexGroupItem.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/functions/ReduceEdgeGroupItems.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/functions/TransposeVertexGroupItems.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/functions/UpdateEdgeGroupItem.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/functions/aggregation/PropertyValueAggregator.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/tuples/EdgeGroupItem.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/tuples/VertexGroupItem.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/grouping/GroupingTestBase.java
* added 3 basic methods to enable parametrization
* introduced type label constant to be used as property key
* minor code cleanups throughout grouping
* fixes #457
=> [#457] refactored grouping convenience functions

gradoop-common/src/main/java/org/gradoop/common/model/impl/id/GradoopId.java, gradoop-common/src/main/java/org/gradoop/common/model/impl/id/GradoopIdSet.java, gradoop-common/src/main/java/org/gradoop/common/storage/impl/hbase/HBaseEPGMStore.java, gradoop-common/src/main/java/org/gradoop/common/storage/impl/hbase/HBaseEdgeHandler.java, gradoop-common/src/main/java/org/gradoop/common/storage/impl/hbase/HBaseElementHandler.java, gradoop-common/src/main/java/org/gradoop/common/storage/impl/hbase/HBaseGraphHeadHandler.java, gradoop-common/src/main/java/org/gradoop/common/storage/impl/hbase/HBaseVertexHandler.java, gradoop-common/src/test/java/org/gradoop/common/model/impl/id/GradoopIdTest.java
* HBase handlers now use toByteArrays instead of Writables util class
* fixes #460
=> [#460] removed Writable interface from GradoopId

gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/common/query/QueryHandler.java
=> [#482] Updated QueryHandler to GDL changes

gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/functions/FilterAndProjectEdge.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/functions/FilterAndProjectVertex.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/FilterAndProjectEdgesTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/FilterAndProjectVerticesTest.java
=> [#484] Added non-predicate tests for Filter operators

gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/FilterAndProjectEdges.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/FilterAndProjectVertices.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/functions/FilterAndProjectEdge.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/functions/FilterAndProjectVertex.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/leaf/FilterAndProjectEdgesNode.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/leaf/FilterAndProjectVerticesNode.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/FilterAndProjectEdgesTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/FilterAndProjectVerticesTest.java
=> #498 Improve API of FilterAndProjectVertices/Edges

gradoop-flink/src/main/java/org/gradoop/flink/model/impl/functions/epgm/ByLabel.java
Created separated class `ByLabel` to filter by label.
=> Extracted FilterFunction from label function.

gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/package-info.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/BinaryNode.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/LeafNode.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/PlanNode.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/QueryPlan.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/UnaryNode.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/binary/ExpandEmbeddingsNode.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/binary/JoinEmbeddingsNode.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/binary/package-info.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/leaf/FilterAndProjectEdgesNode.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/leaf/FilterAndProjectVerticesNode.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/leaf/package-info.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/package-info.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/unary/FilterEmbeddingsNode.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/unary/ProjectEmbeddingsNode.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/unary/package-info.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/MockPlanNode.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/binary/ExpandEmbeddingsNodeTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/binary/JoinEmbeddingsNodeTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/leaf/FilterAndProjectEdgesNodeTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/leaf/FilterAndProjectVerticesNodeTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/unary/FilterEmbeddingsNodeTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/unary/ProjectEmbeddingsNodeTest.java
=> [#508] Moved query plan to separate package

gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/common/query/predicates/CNF.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/common/query/predicates/CNFElement.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/common/query/predicates/PredicateCollection.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/common/query/predicates/QueryComparable.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/common/query/predicates/comparables/ElementSelectorComparable.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/common/query/predicates/comparables/LiteralComparable.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/common/query/predicates/comparables/PropertySelectorComparable.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/common/query/predicates/expressions/ComparisonExpression.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/FilterAndProjectEdges.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/FilterAndProjectEdgesAlt.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/FilterAndProjectVertices.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/FilterAndProjectVerticesAlt.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/functions/FilterAndProjectEdge.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/functions/FilterAndProjectVertex.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/functions/FilterEdge.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/functions/FilterVertex.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/leaf/FilterAndProjectEdgesAltNode.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/leaf/FilterAndProjectEdgesNode.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/leaf/FilterAndProjectVerticesAltNode.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/leaf/FilterAndProjectVerticesNode.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/common/query/predicates/CNFTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/FilterAndProjectEdgesAltTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/FilterAndProjectVerticesAltTest.java
- Add alternative version of Filter and Project using Filter + Map instead of FlatMap
- Make predicate evaluation possible for GraphElements
=> Improve FilterAndProjectVertex/Edge

gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/common/pojos/Embedding.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/common/pojos/EmbeddingFactory.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/common/query/predicates/CNFElementTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/common/query/predicates/CNFTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/common/query/predicates/compareables/PropertySelectorComparableTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/common/pojos/EmbeddingTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/common/pojos/EmbeddingTestUtils.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/PhysicalOperatorTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/FilterEmbeddingsTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/join/JoinEmbeddingsTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/unary/FilterEmbeddingsNodeTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/unary/ProjectEmbeddingsNodeTest.java
Improve Embedding creation by adding
`Embedding.addAll(GradoopId... ids)` and `Embedding.addProperties(PropertyValue... properties)`
=> Improve Embedding

gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/common/query/QueryHandler.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/common/query/Triple.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/common/query/QueryHandlerTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/common/query/TripleTest.java
=> [#533] Add triple support to QueryHandler

gradoop-flink/src/main/java/org/gradoop/flink/io/impl/dot/functions/DOTFileFormat.java, gradoop-flink/src/test/java/org/gradoop/flink/io/impl/dot/DOTDataSinkTest.java
=> [#558] Cleanup and fixing DOT FileFormat

gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/plantable/PlanTableEntry.java
* toString triggered estimator to run
* fixes #565
=> [#565] Fixed PlanTableEntry.toString()

gradoop-checkstyle/src/main/resources/gradoop/checkstyle.xml, gradoop-examples/src/main/java/org/gradoop/examples/grouping/Communities.java, gradoop-examples/src/main/java/org/gradoop/examples/grouping/Composition.java, gradoop-examples/src/main/java/org/gradoop/examples/grouping/Schema.java, gradoop-examples/src/main/java/org/gradoop/examples/io/PokecExample.java, gradoop-examples/src/main/java/org/gradoop/utils/sampling/RandomNodeSamplingRunner.java, gradoop-examples/src/main/java/org/gradoop/utils/sampling/package-info.java
* added few example programs
* added RandomNodeSamplingRunner
* updated PokecExample
* fixes #567
=> [#567] Grouping examples for BTW demo

gradoop-flink/src/main/java/org/gradoop/flink/model/api/functions/GraphHeadReduceFunction.java, gradoop-flink/src/main/java/org/gradoop/flink/model/api/operators/GraphCollectionOperators.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/GraphCollection.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/functions/epgm/IdInBroadcast.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/distinction/DistinctById.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/distinction/DistinctByIsomorphism.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/distinction/GroupByIsomorphism.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/distinction/functions/CountGraphHeads.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/distinction/functions/FirstGraphHead.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/distinction/functions/GraphHeadGroup.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/distinction/functions/IdFromGraphHeadString.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/distinction/functions/package-info.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/distinction/package-info.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/selection/Selection.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/selection/SelectionBase.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/tostring/CanonicalAdjacencyMatrixBuilder.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/distinction/DistinctByIdTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/distinction/DistinctByIsomorphismTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/distinction/DistinctByIsomorphismTestBase.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/distinction/GroupByIsomorphismTest.java
* 2 graph collection operators
* example use case: group by graph (isomorphism) and count occurrences
* fixes #439
=> [#439] added Distinction and Group by by Isomorphism

gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/Grouping.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/GroupingGroupCombine.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/GroupingGroupReduce.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/functions/BuildBase.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/functions/BuildEdgeGroupItem.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/functions/BuildGroupItemBase.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/functions/BuildSuperEdge.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/functions/BuildSuperVertex.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/functions/BuildVertexGroupItem.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/functions/CombineEdgeGroupItems.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/functions/CombineVertexGroupItems.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/functions/ReduceEdgeGroupItems.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/functions/ReduceVertexGroupItemBase.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/functions/ReduceVertexGroupItems.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/functions/TransposeVertexGroupItems.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/functions/UpdateEdgeGroupItem.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/tuples/EdgeGroupItem.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/tuples/GroupItem.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/tuples/LabelGroup.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/tuples/VertexGroupItem.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/grouping/GroupingTestBase.java
Added label specific grouping, so that it is possible to set different grouping properties for different labels.
Also added label specific aggregators accordingly.
=> Label specific grouping

gradoop-flink/src/main/java/org/gradoop/flink/datagen/transactions/foodbroker/config/FoodBrokerConfig.java, gradoop-flink/src/main/java/org/gradoop/flink/datagen/transactions/foodbroker/functions/masterdata/BusinessRelation.java, gradoop-flink/src/main/java/org/gradoop/flink/datagen/transactions/foodbroker/generators/BusinessRelationGenerator.java, gradoop-flink/src/main/java/org/gradoop/flink/datagen/transactions/foodbroker/generators/CustomerGenerator.java, gradoop-flink/src/main/java/org/gradoop/flink/datagen/transactions/foodbroker/generators/VendorGenerator.java, gradoop-flink/src/test/java/org/gradoop/flink/datagen/transactions/foodbroker/FoodBrokerConfigTest.java
Changed the constructor of the foodbroker config to be loaded by a JSON string containing the configuration. Therefore updated the factory method `fromFile(String configPath, String resourcePath)` and added a new method `fromJSONString(String configString, String resourcePath)`.
=> [#613] Updated config file to be loaded from a json string.

gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/GraphCollection.java, gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/LogicalGraph.java, gradoop-flink/src/main/java/org/gradoop/flink/model/api/layouts/GraphCollectionLayout.java, gradoop-flink/src/main/java/org/gradoop/flink/model/api/layouts/GraphCollectionLayoutFactory.java, gradoop-flink/src/main/java/org/gradoop/flink/model/api/layouts/LogicalGraphLayout.java, gradoop-flink/src/main/java/org/gradoop/flink/model/api/layouts/LogicalGraphLayoutFactory.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/layouts/gve/GVEBaseFactory.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/layouts/gve/GVECollectionLayoutFactory.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/layouts/gve/GVEGraphLayoutFactory.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/layouts/gve/GVELayout.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/layouts/gve/indexed/IndexedGVECollectionLayoutFactory.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/layouts/gve/indexed/IndexedGVEGraphLayoutFactory.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/layouts/gve/indexed/IndexedGVELayout.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/layouts/gve/indexed/package-info.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/layouts/transactional/TxCollectionLayout.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/layouts/transactional/TxCollectionLayoutFactory.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/layouts/GraphCollectionLayoutFactoryTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/layouts/LogicalGraphLayoutFactoryTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/layouts/gve/GVEGraphLayoutFactoryTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/layouts/gve/GVELayoutTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/layouts/gve/indexed/IndexedGVECollectionLayoutFactoryTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/layouts/gve/indexed/IndexedGVEGraphLayoutFactoryTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/layouts/gve/indexed/IndexedGVELayoutTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/layouts/transactional/TxCollectionLayoutFactoryTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/layouts/transactional/TxCollectionLayoutTest.java
* provides access to label-partitioned data sets
* required for performance optimizations in Cypher engine
=> [#533] Add IndexedGVELayout

gradoop-flink/src/main/java/org/gradoop/flink/io/impl/dot/functions/DOTFileFormat.java, gradoop-flink/src/test/java/org/gradoop/flink/io/impl/dot/DOTDataSinkTest.java, gradoop-flink/src/test/resources/data/dot/input.gdl
=> [#666] escape all html4 entities in DOT labels

gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/LogicalGraph.java, gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/LogicalGraphOperators.java
=> [#673] Add convenience method for Cypher matching

gradoop-common/src/main/java/org/gradoop/common/model/api/entities/EPGMAttributed.java, gradoop-common/src/main/java/org/gradoop/common/model/impl/pojo/Element.java, gradoop-flink/src/main/java/org/gradoop/flink/datagen/transactions/foodbroker/functions/process/ComplaintHandling.java, gradoop-flink/src/main/java/org/gradoop/flink/io/impl/csv/functions/ElementToPropertyMetaData.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/drilling/functions/transformations/DrillDownTransformation.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/transactional/function/AddMatchesToProperties.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/statistics/functions/ExtractPropertyValues.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/statistics/functions/ExtractPropertyValuesByLabel.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/transactional/TransactionalPatternMatchingTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/split/SplitTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/subgraph/SubgraphTest.java, gradoop-hbase/src/main/java/org/gradoop/common/storage/impl/hbase/HBaseElement.java
* added @Nullable annotation to Element.getProperties to give compiler warnings
* fixes #679
=> [#679] Add missing null checks before properties access

gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/limit/Limit.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/limit/LimitTest.java
=> [#680] Change filter condition in Limit to InAnyGraph

gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/aggregation/ApplyAggregation.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/aggregation/functions/AggregateTransactions.java, gradoop-flink/src/test/java/org/gradoop/flink/model/GradoopFlinkTestBase.java
=> [#711] Add optimized execution path for Tx Layout in ApplyAggregation

gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/selection/Selection.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/selection/functions/FilterTransactions.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/selection/functions/package-info.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/selection/SelectionTest.java
=> [#713] Add optimized execution path for Tx Layout in Selection

gradoop-common/pom.xml, gradoop-hbase/pom.xml, pom.xml
I recreate it for bug fix #736
=> [#736]delete unused change and fix pom

README.md
The mention of Apache HBase was removed in README.md
=> (#757) updated readme.md

gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/LogicalGraph.java, gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/LogicalGraphOperators.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/subgraph/Subgraph.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/subgraph/SubgraphTest.java
* also adds validation strategy for regular subgraph
* fixes #796
=> Add project strategy to edge induced subgraph

.travis.yml, gradoop-common/src/main/java/org/gradoop/common/model/impl/properties/PropertyValue.java, gradoop-common/src/test/java/org/gradoop/common/model/impl/properties/PropertyValueTest.java
=> [#802] fixed return class objects in getType function

gradoop-common/src/main/java/org/gradoop/common/model/impl/properties/PropertyValue.java, gradoop-common/src/test/java/org/gradoop/common/model/impl/properties/PropertyValueTest.java
=> [#810] added time data types to compare method of PropertyValue class

gradoop-examples/src/main/java/org/gradoop/utils/sampling/RandomVertexSamplingRunner.java, gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/LogicalGraph.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/sampling/RandomVertexSampling.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/sampling/RandomVertexSamplingTest.java
=> #836 rename RandomNodeSampling

gradoop-common/src/main/java/org/gradoop/common/model/impl/properties/PropertyValueUtils.java, gradoop-common/src/test/java/org/gradoop/common/model/impl/properties/PropertyValueUtilsTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/aggregation/ApplyAggregationTest.java
=> [#830] Add PropertyValueUtilsTest and fix operator bugs

gradoop-examples/src/main/java/org/gradoop/utils/sampling/RandomEdgeSamplingRunner.java, gradoop-examples/src/main/java/org/gradoop/utils/sampling/RandomNonUniformVertexSamplingRunner.java, gradoop-examples/src/main/java/org/gradoop/utils/sampling/RandomVertexSamplingRunner.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/sampling/RandomEdgeSampling.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/sampling/RandomNonUniformVertexSampling.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/sampling/RandomVertexSampling.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/sampling/functions/AddMaxDegreeCrossFunction.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/sampling/functions/NonUniformVertexRandomFilter.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/sampling/functions/RemoveUnnecessaryPropertiesMap.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/sampling/functions/VertexToDegreeMap.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/sampling/RandomNonUniformVertexSamplingTest.java
=> #848 nonuniform vertex sampling

gradoop-common/src/main/java/org/gradoop/common/model/impl/properties/PropertyValue.java, gradoop-common/src/main/java/org/gradoop/common/model/impl/properties/PropertyValueUtils.java, gradoop-common/src/test/java/org/gradoop/common/model/impl/properties/PropertyValueTest.java
=> [#398] Add support for comparison of different PropertyValue number types

LICENSE, NOTICE, gradoop-flink/src/main/java/org/gradoop/flink/io/impl/csv/indexed/functions/MultipleFileOutputFormat.java
- added NOTICE file
- added licence information about subcomponents to LICENCE file
- added copy NOTE to MultipleFileOutputFormat
=> [#861] update licence handling

gradoop-examples/src/main/java/org/gradoop/utils/sampling/RandomVertexEdgeSamplingRunner.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/sampling/RandomVertexEdgeSampling.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/sampling/functions/RandomFilter.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/sampling/RandomVertexEdgeSamplingTest.java
=> [#872] add RandomVertexEdgeSampling

gradoop-store/gradoop-hbase/src/main/java/org/gradoop/common/config/GradoopHBaseConfig.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/common/storage/impl/hbase/HBaseEPGMStore.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/common/storage/impl/hbase/api/ElementHandler.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/common/storage/impl/hbase/factory/HBaseEPGMStoreFactory.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/common/storage/impl/hbase/handler/HBaseEdgeHandler.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/common/storage/impl/hbase/handler/HBaseElementHandler.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/common/storage/impl/hbase/handler/HBaseGraphElementHandler.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/common/storage/impl/hbase/handler/HBaseGraphHeadHandler.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/common/storage/impl/hbase/handler/HBaseVertexHandler.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/flink/io/impl/hbase/HBaseDataSink.java
replaced deprecated api usage of hbase store and reordered params of HBase config class constructor
fixes #862
=> [#862] replaced deprecated api usage of hbase store 

gradoop-store/gradoop-hbase/src/test/java/org/gradoop/GradoopHBaseTestBase.java, pom.xml
=> [#885] upgraded hbase dependency to 1.4.3 and removed unused imports

gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/aggregation/AggregationTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/aggregation/ApplyAggregationTest.java
* add base-case tests for HasEdgeLabel
* add base-case tests for HasVertexLabel
* add edge-case tests for HasEdgeLabel
* add edge-case tests for HasVertexLabel
fixes #935
=> [#935] Add tests for containment functions

.travis.yml
=> WIP: [#998] enable travis multi os testing

gradoop-flink/src/test/java/org/gradoop/flink/algorithms/gelly/clusteringcoefficient/GellyLocalClusteringCoefficientDirectedTest.java, gradoop-flink/src/test/java/org/gradoop/flink/algorithms/gelly/clusteringcoefficient/GellyLocalClusteringCoefficientUndirectedTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/sampling/statistics/AverageClusteringCoefficientTest.java
=> [#1072] Added delta for assertEquals double

gradoop-flink/src/main/java/org/gradoop/flink/io/impl/csv/CSVBase.java
=> [#1078] improve parallel execution of CSVSink

README.md, gradoop-flink/pom.xml, pom.xml
=> [#1084] updated flink to v.1.6.0

gradoop-checkstyle/pom.xml, gradoop-common/pom.xml, gradoop-data-integration/pom.xml, gradoop-examples/pom.xml, gradoop-flink/pom.xml, gradoop-store/gradoop-accumulo/pom.xml, gradoop-store/gradoop-hbase/pom.xml, gradoop-store/gradoop-store-api/pom.xml, gradoop-store/pom.xml, pom.xml
=> [#1097] prepared further development

gradoop-checkstyle/src/main/resources/gradoop/checkstyle.xml, gradoop-common/src/main/java/org/gradoop/common/model/impl/id/GradoopId.java, gradoop-common/src/test/java/org/gradoop/common/model/impl/properties/PropertyValueUtilsTest.java, gradoop-examples/src/main/java/org/gradoop/examples/patternmatching/PatternMatchingRunner.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/preserving/explorative/traverser/SetPairBulkTraverser.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/preserving/explorative/traverser/SetPairForLoopTraverser.java, gradoop-flink/src/test/java/org/gradoop/flink/algorithms/fsm/transactional/basic/BasicPatternsTransactionalFSMTestBase.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/SubgraphHomomorphismTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/SubgraphIsomorphismTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/CypherGraphConstructionTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/CypherPatternMatchingHomomorphismTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/CypherPatternMatchingIsomorphismTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/common/pojos/EmbeddingTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/simulation/dual/DualSimulationTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/transactional/TransactionalPatternMatchingTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/sampling/PageRankSamplingTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/sampling/RandomEdgeSamplingTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/sampling/RandomLimitedDegreeVertexSamplingTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/sampling/RandomNonUniformVertexSamplingTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/sampling/RandomVertexEdgeSamplingTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/sampling/RandomVertexNeighborhoodSamplingTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/sampling/RandomVertexSamplingTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/sampling/statistics/AverageClusteringCoefficientTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/sampling/statistics/ConnectedComponentsDistributionTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/sampling/statistics/ValueConnectedComponentsTest.java, gradoop-store/gradoop-hbase/src/test/java/org/gradoop/storage/impl/hbase/predicate/filter/impl/HBasePropEqualsTest.java, gradoop-store/gradoop-hbase/src/test/java/org/gradoop/storage/impl/hbase/predicate/filter/impl/HBasePropLargerThanTest.java
Edited existing array initilizations accordingly.
Fixes #1107
=> [#1107] Added array initilization indent to the checkstyle. 

gradoop-store/gradoop-hbase/src/main/java/org/gradoop/storage/config/GradoopHBaseConfig.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/storage/impl/hbase/HBaseEPGMStore.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/storage/impl/hbase/api/ElementHandler.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/storage/impl/hbase/handler/HBaseEdgeHandler.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/storage/impl/hbase/handler/HBaseElementHandler.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/storage/impl/hbase/handler/HBaseGraphElementHandler.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/storage/impl/hbase/handler/HBaseVertexHandler.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/storage/impl/hbase/io/inputformats/BaseTableInputFormat.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/storage/impl/hbase/io/inputformats/EdgeTableInputFormat.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/storage/impl/hbase/io/inputformats/GraphHeadTableInputFormat.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/storage/impl/hbase/io/inputformats/VertexTableInputFormat.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/storage/impl/hbase/predicate/filter/HBaseFilterUtils.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/storage/utils/RegionSplitter.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/storage/utils/RowKeyDistributor.java, gradoop-store/gradoop-hbase/src/test/java/org/gradoop/storage/impl/hbase/GradoopHBaseTestBase.java, gradoop-store/gradoop-hbase/src/test/java/org/gradoop/storage/impl/hbase/HBaseDefaultGraphStoreTest.java, gradoop-store/gradoop-hbase/src/test/java/org/gradoop/storage/impl/hbase/HBaseEPGMStoreTest.java, gradoop-store/gradoop-hbase/src/test/java/org/gradoop/storage/impl/hbase/HBaseSplitRegionGraphStoreTest.java, gradoop-store/gradoop-hbase/src/test/java/org/gradoop/storage/impl/hbase/HBaseSpreadingByteGraphStoreTest.java, gradoop-store/gradoop-hbase/src/test/java/org/gradoop/storage/impl/hbase/HBaseTestSuite.java, gradoop-store/gradoop-hbase/src/test/java/org/gradoop/storage/impl/hbase/io/HBaseDataSinkSourceTest.java
=> [#1133] Added pre-split region and spreading byte option to HBase store

gradoop-flink/src/main/java/org/gradoop/flink/io/impl/csv/metadata/CSVMetaData.java
=> [#1152] Fix typo in CSVMetaData

gradoop-data-integration/src/main/java/org/gradoop/dataintegration/importer/impl/csv/MinimalCSVImporter.java
Use `FileSystem.open` instead of a `FileInputStream` to also support HDFS paths.
fixes #1154
=> [#1154] Fix HDFS issues with MinimalCSVImporter.

gradoop-flink/src/main/java/org/gradoop/flink/io/impl/csv/metadata/CSVMetaDataParser.java
=> [#1168] Fix typo in CSVMetaDataParser and minor refactor

gradoop-flink/src/main/java/org/gradoop/flink/io/impl/csv/metadata/CSVMetaDataSource.java
=> [#1177] Throw exception when CSVMetaDataSource.readLocal does not find file

.travis.yml
=> [#1182] Remove osx build from allow_failures

gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/verify/Verify.java
=> [#1202] Fix type parameter order of Verify.

gradoop-store/gradoop-hbase/src/main/java/org/gradoop/storage/impl/hbase/HBaseEPGMStore.java, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/storage/impl/hbase/io/HBaseDataSink.java, gradoop-store/gradoop-hbase/src/test/java/org/gradoop/storage/impl/hbase/HBaseEPGMStoreTest.java, gradoop-store/gradoop-hbase/src/test/java/org/gradoop/storage/impl/hbase/io/HBaseDataSinkSourceTest.java
=> [#1204] Add support for overwrite in HBase store.

gradoop-common/src/main/java/org/gradoop/common/model/impl/properties/PropertyValue.java
=> [1176] Use highest bit for FLAG_LARGE

gradoop-common/src/main/java/org/gradoop/common/model/impl/properties/PropertyValue.java, gradoop-common/src/main/java/org/gradoop/common/model/impl/properties/strategies/BigDecimalStrategy.java, gradoop-common/src/test/java/org/gradoop/common/model/impl/properties/PropertyValueTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/aggregation/ApplyAggregationTest.java
=> [#845] Remove conversion from property value getters

gradoop-checkstyle/pom.xml, gradoop-common/pom.xml, gradoop-data-integration/pom.xml, gradoop-examples/pom.xml, gradoop-flink/pom.xml, gradoop-store/gradoop-accumulo/pom.xml, gradoop-store/gradoop-hbase/pom.xml, gradoop-store/gradoop-store-api/pom.xml, gradoop-store/pom.xml, pom.xml
=> [#1226] prepare further development

gradoop-common/src/main/java/org/gradoop/common/model/impl/properties/PropertyValueList.java, gradoop-common/src/test/java/org/gradoop/common/model/impl/properties/PropertyValueListTest.java
* iterator next() method now raises NoSuchElementException when list is empty
* add test to check expected behavior
fixes #1241
=> [#1241] Fix PropertyValueListIterator implementation

gradoop-checkstyle/src/main/resources/gradoop/checkstyle.xml
=> [#1245] Changed Checkstyle dtd path + moved cache property

gradoop-common/src/main/java/org/gradoop/common/model/impl/properties/strategies/NullStrategy.java
* getRawBytes() now returns byte array containing only null
=> [#1249] Change return value of NullStrategy.getRawBytes

README.md
[#1232] updated readme to contain all operators and modules. Also added link to the wiki and xml syntax highlighting
The list of operators is quite long now, we could consider moving it into the wiki.
=> [#1232] update readme

gradoop-flink/src/main/java/org/gradoop/flink/io/impl/gdl/GDLEncoder.java
=> [#1258] Fix print for graph collections

gradoop-examples/gradoop-examples-operators/pom.xml, gradoop-examples/pom.xml
* added version information to gradoop-example pom
* added profiles to gradoop-example-generators pom
=> [#1289] fix maven site generation in examples module

gradoop-data-integration/src/main/java/org/gradoop/dataintegration/transformation/impl/PropertyTransformation.java, gradoop-flink/src/main/java/org/gradoop/flink/io/impl/gdl/GDLConsoleOutput.java, gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/BaseGraph.java, gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/BaseGraphCollection.java, gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/BaseGraphCollectionFactory.java, gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/BaseGraphCollectionOperators.java, gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/BaseGraphFactory.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/epgm/GraphCollection.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/epgm/GraphCollectionFactory.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/epgm/LogicalGraph.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/aggregation/Aggregation.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/Grouping.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/GroupingGroupCombine.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/GroupingGroupReduce.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/subgraph/Subgraph.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/transformation/Transformation.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/verify/Verify.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/verify/VerifyGraphContainment.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/verify/VerifyGraphsContainment.java, gradoop-flink/src/main/java/org/gradoop/flink/util/GradoopFlinkConfig.java
=> [#1302] Add BaseGraph as generic type to BaseGraphCollection

gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/BaseGraphCollection.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/epgm/GraphCollection.java
=> [#1312] Add getGraphFactory

gradoop-common/src/test/java/org/gradoop/common/util/AsciiGraphLoaderTest.java
=> [#1324] Fix syntax error in test graph.

gradoop-flink/src/main/java/org/gradoop/flink/model/impl/functions/epgm/BySourceId.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/functions/epgm/ByTargetId.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/functions/graphcontainment/InAllGraphs.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/aggregation/functions/containment/HasLabel.java
=> [#1358] Use Element interfaces instead of the EPGM implementations in filters

gradoop-checkstyle/pom.xml, gradoop-common/pom.xml, gradoop-data-integration/pom.xml, gradoop-examples/gradoop-examples-operators/pom.xml, gradoop-examples/pom.xml, gradoop-flink/pom.xml, gradoop-store/gradoop-accumulo/pom.xml, gradoop-store/gradoop-hbase/pom.xml, gradoop-store/gradoop-store-api/pom.xml, gradoop-store/pom.xml, pom.xml
=> [#1372] bumped version to 0.6.0-SNAPSHOT

gradoop-flink/src/main/java/org/gradoop/flink/io/impl/csv/metadata/CSVMetaDataSource.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/cypher/capf/query/functions/PropertyEncoder.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/cypher/capf/result/functions/PropertyDecoder.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/common/statistics/GraphStatisticsHDFSReader.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/common/statistics/GraphStatisticsLocalFSReader.java
=> [#1383] Replace usage of Charset.forName with StandardCharsets

gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/common/statistics/GraphStatisticsHDFSReaderTest.java
=> [#1384] Remove Ignore from GraphStatisticsHDFSReaderTest

gradoop-flink/src/main/java/org/gradoop/flink/io/impl/statistics/GraphStatisticsDataSink.java
=> [#1393] Add overwrite parameter to writeCSV method call

.github/workflows/maven.yml
Added install to maven action
#1447 
Building an archetype with tests requires an installation step of the needed project artifacts. 
self-triggered
=> [#1447] add install to maven action

gradoop-common/src/main/java/org/gradoop/common/util/AsciiGraphLoader.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/common/query/QueryHandler.java, pom.xml
Using `BailSyntaxErrorStrategy` in QueryHandler and AsciiGraphLoader
#1438 
To achieve a clean error handling the errors within a gdl string should be thrown as exceptions instead of being logged to console.
Unit testing
=> [#1438] Improve GDL error handling

README.md, gradoop-checkstyle/pom.xml, gradoop-common/pom.xml, gradoop-data-integration/pom.xml, gradoop-examples/gradoop-examples-operators/pom.xml, gradoop-examples/gradoop-examples-temporal/pom.xml, gradoop-examples/pom.xml, gradoop-flink/pom.xml, gradoop-quickstart/pom.xml, gradoop-store/gradoop-accumulo/pom.xml, gradoop-store/gradoop-hbase/pom.xml, gradoop-store/gradoop-store-api/pom.xml, gradoop-store/pom.xml, gradoop-temporal/pom.xml, pom.xml
Prepared release 0.5.2
#1488 
Next release.
=> [#1488] prepared release 0.5.2

gradoop-checkstyle/pom.xml, gradoop-common/pom.xml, gradoop-data-integration/pom.xml, gradoop-examples/gradoop-examples-operators/pom.xml, gradoop-examples/gradoop-examples-temporal/pom.xml, gradoop-examples/pom.xml, gradoop-flink/pom.xml, gradoop-quickstart/pom.xml, gradoop-store/gradoop-accumulo/pom.xml, gradoop-store/gradoop-hbase/pom.xml, gradoop-store/gradoop-store-api/pom.xml, gradoop-store/pom.xml, gradoop-temporal/pom.xml, pom.xml
Reset gradoop version to 0.6.0-SNAPSHOT
#1494
=> [#1494] prepared further development

NOTICE-binary, gradoop-common/pom.xml, gradoop-common/src/main/java/org/gradoop/common/model/impl/properties/PropertyValueList.java, gradoop-flink/src/main/java/org/gradoop/flink/algorithms/fsm/transactional/tle/canonicalization/CanonicalLabeler.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/expand/functions/AdoptEmptyPaths.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/join/functions/ExtractJoinColumns.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/join/functions/ExtractPropertyJoinColumns.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/join/functions/ExtractJoinColumnsTest.java, gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/join/functions/ExtractPropertyJoinColumnsTest.java, gradoop-quickstart/src/main/resources/archetype-resources/pom.xml, gradoop-store/gradoop-hbase/src/main/java/org/gradoop/storage/hbase/config/GradoopHBaseConfig.java, pom.xml
Updated the version of commons-lang dependency from 2.6 to 3.11.
Blocks #1482 
Using the old version leads to some serialization errors in issue #1482.
Run unit tests.
=> [#1516] Updated version of Apache commons-lang from 2.6 to 3.11

gradoop-flink/pom.xml, gradoop-flink/src/main/java/org/gradoop/flink/algorithms/fsm/transactional/tle/functions/CategoryGraphCounts.java, gradoop-flink/src/main/java/org/gradoop/flink/algorithms/gelly/labelpropagation/functions/LPUpdateFunction.java, gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/simulation/dual/functions/ValidateNeighborhood.java, pom.xml
Updated Flink Version to `1.9.3` including flink-shaded-hadoop-2 update to `2.6.5-9.0`
#1505 
- Problems with deadlocks on Flink 1.7.2
- Flink 1.7.2 is outdated
=> [#1505] bumped Flink version to 1.9.3

README.md, gradoop-checkstyle/pom.xml, gradoop-common/pom.xml, gradoop-data-integration/pom.xml, gradoop-examples/gradoop-examples-operators/pom.xml, gradoop-examples/gradoop-examples-temporal/pom.xml, gradoop-examples/pom.xml, gradoop-flink/pom.xml, gradoop-quickstart/pom.xml, gradoop-store/gradoop-accumulo/pom.xml, gradoop-store/gradoop-hbase/pom.xml, gradoop-store/gradoop-store-api/pom.xml, gradoop-store/pom.xml, gradoop-temporal/pom.xml, pom.xml
Bumped all poms to 0.6.0. Prepared next stable release.
#1534
=> [#1534] prepare stable release 0.6.0
