- gradoop-core/src/main/java/org/gradoop/model/impl/properties/PropertyValueList.java
- gradoop-examples/src/main/java/org/gradoop/examples/grouping/GroupingRunner.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/LogicalGraph.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/Grouping.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/GroupingGroupReduce.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/BuildBase.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/BuildEdgeGroupItem.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/BuildSuperEdge.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/BuildSuperVertex.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/BuildVertexGroupItem.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/CombineEdgeGroupItems.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/ReduceEdgeGroupItems.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/functions/ReduceVertexGroupItems.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/tuples/EdgeGroupItem.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/grouping/tuples/VertexGroupItem.java
- gradoop-flink/src/test/java/org/gradoop/model/impl/operators/grouping/GroupingTestBase.java
Aggregate properties are managed using `PropertyValueList`, which is analogous to grouping properties.
Fixes #128
> Add support for multiple aggregate functions in grouping

- gradoop-examples/src/main/java/org/gradoop/examples/biiig/CategoryCharacteristicPatterns.java
- gradoop-examples/src/main/java/org/gradoop/examples/sna/SNABenchmark2.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/aggregation/ApplyAggregation.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/aggregation/functions/LeftOuterPropertySetter.java
- gradoop-flink/src/test/java/org/gradoop/model/impl/operators/aggregation/AggregationTest.java
When given a GraphCollection with at least one LogicalGraph that has no vertices or edges, ApplyAggregation does not return any new value. The reason is that the Co-Grouping of the AggregationFunctions returns empty groups for these graphs. A possible fix is a left outer join, setting the new property to a user-defined default element.
Using a left outer join makes the aggregation of empty graphs (without vertices and/or edges) possible.
It is now necessary to provide a default property value for these graphs.
> #158 ApplyAggregation does not return any value for LogicalGraphs without vertices

- gradoop-algorithms/src/main/java/org/gradoop/model/impl/algorithms/btgs/BusinessTransactionGraphs.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/functions/epgm/ElementIdUpdater.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/functions/tuple/Value0Of4.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/cloning/Cloning.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/subgraph/ApplySubgraph.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/subgraph/functions/AddGraphsToElements.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/subgraph/functions/AddGraphsToElementsCoGroup.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/subgraph/functions/EdgesWithNewGraphsTuple.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/subgraph/functions/ElementIdGraphIdTuple.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/subgraph/functions/FilterEdgeGraphs.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/subgraph/functions/IdSourceTargetGraphTuple.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/subgraph/functions/JoinTuplesWithNewGraphs.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/subgraph/functions/JoinWithSourceGraphIdSet.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/subgraph/functions/JoinWithTargetGraphIdSet.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/subgraph/functions/MergeEdgeGraphs.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/subgraph/functions/MergeTupleGraphs.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/subgraph/functions/SourceTargetIdGraphsTuple.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/operators/subgraph/functions/package-info.java
- gradoop-flink/src/test/java/org/gradoop/model/impl/operators/subgraph/SubgraphTest.java
Created class ApplySubgraph that implements ApplicableUnaryGraphToGraphOperator. Through this, the subgraph operator is now applicable to GraphCollections.
Implemented various functions in package org.gradoop.model.impl.operators.subgraph.functions used by ApplySubgraph.
Moved ElementIdUpdater to org.gradoop.model.impl.functions.epgm because its now used outside of cloning.
Added Value0Of4 function.
Changed ExpandGradoopIds to be applicable to any Tuple2 containing a GradoopIdSet in its second field. Also added documentation and function annotations.
> Implemented operator ApplySubgraph, #161

- gradoop-flink/src/main/java/org/gradoop/model/impl/GraphCollection.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/functions/epgm/GraphElementExpander.java
- gradoop-flink/src/main/java/org/gradoop/model/impl/functions/epgm/GraphElementsHeadsToTransaction.java
The `toTransaction()` method is realized by unifying the vertices and edges in a dataset of EPGMElement. After that, a groupFunction builds the transaction graph for the  EPGMElements and the GraphHead that belong to the same graph.
> bug fix of toTransaction method

- gradoop-examples/src/main/java/org/gradoop/benchmark/grouping/GroupingBenchmark.java
- gradoop-examples/src/main/java/org/gradoop/benchmark/patternmatching/Queries.java
- gradoop-examples/src/main/java/org/gradoop/benchmark/patternmatching/TraverserBenchmark.java
- gradoop-examples/src/main/java/org/gradoop/benchmark/patternmatching/package-info.java
- gradoop-examples/src/main/java/org/gradoop/examples/patternmatching/PatternMatchingRunner.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/api/operators/LogicalGraphOperators.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/LogicalGraph.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/common/functions/ElementHasCandidate.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/common/query/Step.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/common/query/TraversalCode.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/preserving/explorative/ExplorativePatternMatching.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/preserving/explorative/IterationStrategy.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/preserving/explorative/functions/BuildEdgeStep.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/preserving/explorative/functions/BuildEmbeddingWithTiePoint.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/preserving/explorative/functions/UpdateEdgeMappings.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/preserving/explorative/functions/UpdateVertexMappings.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/preserving/explorative/traverser/BulkTraverser.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/preserving/explorative/traverser/DistributedTraverser.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/preserving/explorative/traverser/ForLoopTraverser.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/preserving/explorative/traverser/package-info.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/preserving/explorative/ExplorativeHomomorphismBulkTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/preserving/explorative/ExplorativeHomomorphismLoopUnrollingTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/preserving/explorative/ExplorativeIsomorphismBulkTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/preserving/explorative/ExplorativeIsomorphismLoopUnrollingTest.java
* adds an alternative implementation of `DistributedTraverser` in `ExplorativePatternMatching`
* for-loop iteration offers the advantage to set additional field forwarding informations to distributed joins
> [#359] Added for-loop traverser implementation

- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/transactional/TransactionalPatternMatching.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/transactional/function/BuildGraphWithCandidates.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/transactional/function/BuildIdWithCandidatesAndGraphs.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/transactional/function/ExpandFirstField.java
Now it uses a join instead of broadcast to remove unnecessary transactions.
> Improved transactional matching preprocessing.

- gradoop-common/src/main/java/org/gradoop/common/model/impl/id/GradoopId.java
- gradoop-common/src/main/java/org/gradoop/common/model/impl/properties/PropertyValue.java
- gradoop-common/src/test/java/org/gradoop/common/model/impl/id/GradoopIdTest.java
* equals, hashCode and compareTo directly operate on the byte[]
* fixes #459
> [#459] using byte[] to represent GradoopId internally

- gradoop-common/src/main/java/org/gradoop/common/model/impl/properties/PropertyValue.java
- gradoop-common/src/test/java/org/gradoop/common/GradoopTestUtils.java
- gradoop-common/src/test/java/org/gradoop/common/model/impl/properties/PropertyValueTest.java
- gradoop-common/src/test/java/org/gradoop/common/storage/impl/hbase/HBaseGraphStoreTest.java
Fixes #265 
This adds support for `List` and `Map` in `PropertyValue`.
The list and maps must be parameterized as PropertyValue
```java
List<PropertyValue> list = new ArrayList<>();
list.add(PropertyValue.create(42));
list.add(PropertyValue.create("foo"));
PropertyValue listProperty = ProperyValue.create(list);
assertEquals(list, listProperty.getList());
Map<PropertyValue, PropertyValue> map = new HashMap<>();
map.put(PropertyValue.create(42), PropertyValue("42"));
map.put(PropertyValue.create(21), PropertyValue("21"));
PropertyValue mapProperty = ProperyValue.create(map);
assertEquals(map, mapProperty.getMap());
```
> Add support for List and Map property values

- gradoop-common/src/main/java/org/gradoop/common/model/impl/pojo/GraphHead.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/common/functions/AddGraphElementToNewGraph.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/common/functions/ElementsFromEmbedding.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/PatternMatching.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/preserving/explorative/ExplorativePatternMatching.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/common/functions/AddGraphElementToNewGraphTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/common/functions/ElementsFromEmbeddingTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/PatternMatchingTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/PatternMatchingWithBindingTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/preserving/SubgraphHomomorphismTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/preserving/SubgraphIsomorphismTest.java
Fixes #221 
This adds binding information to the matched subgraphs.
Every `GraphHead` contains a property representing the variable mapping for the matched sub graph
```java
LogicalGraph graph = //....
GraphCollection matches = graph.match("(a)-[e]->(b)");
Map<PropertyValue, PropertyValue> variableMapping = 
matches.getGraphHeads().collect().get(0)
.getPropertyValue(PatternMatching.VARIABLE_MAPPING_KEY).getMap();
variableMapping.get(PropertyValue.create("a") //-> Id of the vertex mapped to (a)
```
> [#221] Add variable binding to matching

- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/common/query/QueryHandler.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/common/query/QueryHandlerTest.java
> Extend QueryHandler

- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/functions/epgm/GraphHeadProperties.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/functions/epgm/Properties.java
This class uses an EPGMElement to extract the properties (e.g.) from the GraphHead, as required in #491 .
> Properties mapping class for EPGMElement implemented

- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/common/query/predicates/CNF.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/common/query/predicates/CNFTest.java
Fixes #514 
This adds a more general version to find evaluable disjunctions for given variable set
This method matches all disjunctions of the cnf that are covered by the given variable set. The matched disjunctions are removed from the source CNF and returned as a new CNF
> Add more general version to find evaluable disjunctions for given variable set

- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/common/pojos/Embedding.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/join/JoinEmbeddings.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/join/functions/MergeEmbeddings.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/binary/JoinEmbeddingsNode.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/join/JoinEmbeddingsTest.java
* pre-compute non-join columns
* perform distinctiveness check only when necessary
* replace list iterations with array iterations
* fixes #545
> [#545] Improve MergeEmbeddings

- gradoop-flink/src/main/java/org/gradoop/flink/io/impl/csv/CSVBase.java
- gradoop-flink/src/main/java/org/gradoop/flink/io/impl/csv/CSVDataSink.java
- gradoop-flink/src/main/java/org/gradoop/flink/io/impl/csv/CSVDataSource.java
- gradoop-flink/src/test/java/org/gradoop/flink/io/impl/csv/CSVDataSinkTest.java
* CSV DataSink now either computes the meta data from the specified graph or loads it from a file
* fixes #561
> [#561] Add meta data reuse option CSV data sink

- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/PhysicalOperator.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/cartesian/CartesianProduct.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/expand/ExpandEmbeddings.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/expand/ExpandEmbeddingsBulk.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/expand/ExpandEmbeddingsForLoop.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/FilterAndProjectEdges.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/FilterAndProjectEdgesAlt.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/FilterAndProjectTriples.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/FilterAndProjectVertices.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/FilterAndProjectVerticesAlt.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/filter/FilterEmbeddings.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/join/JoinEmbeddings.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/join/ValueJoin.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/project/ProjectEdges.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/project/ProjectEmbeddings.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/operators/project/ProjectVertices.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/binary/ExpandEmbeddingsNode.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/binary/JoinEmbeddingsNode.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/leaf/FilterAndProjectEdgesNode.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/leaf/FilterAndProjectVerticesNode.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/unary/FilterEmbeddingsNode.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/queryplan/unary/ProjectEmbeddingsNode.java
Fixes #572 
Adds operator names to all cypher (sub-) operators
Example:
> Add names to cypher pattern matching operators

- gradoop-examples/src/main/java/org/gradoop/examples/patternmatching/CypherExample.java
- gradoop-flink/src/main/java/org/gradoop/flink/io/impl/tlf/functions/TLFGraphFromText.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/common/statistics/GraphStatisticsLocalFSReader.java
- gradoop-flink/src/test/java/org/gradoop/flink/datagen/transactions/foodbroker/FoodBrokerTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/io/impl/csv/CSVDataSinkTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/io/impl/csv/CSVDataSourceTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/io/impl/tlf/TLFDataSinkTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/common/statistics/GraphStatisticsHDFSReaderTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/common/statistics/GraphStatisticsLocalFSReaderTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/QueryEngineITTests.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/estimation/EstimatorTestBase.java
There are two main differences between Windows and Linux addressed in this PR: Line endings are \r\n instead of just \n and the conversion from URL (acquired via `class.getResource(...)` has a mandatory slash as the first character, which isn't a valid path in Windows).
With these changes I was able to run all tests successfully on Windows 7 with Hadoop 2.6.0.
> Windows compatibility in tests

- .gitignore
Just like the *.iml from IntelliJ. These types of files are specific for the development environment of each contributor, they should not accidentally become part of the code base.
> Ignore eclipse specific configuration files

- gradoop-flink/src/main/java/org/gradoop/flink/io/impl/dot/DOTDataSink.java
- gradoop-flink/src/main/java/org/gradoop/flink/io/impl/dot/functions/DOTFileFormat.java
- gradoop-flink/src/test/java/org/gradoop/flink/io/impl/dot/DOTDataSinkTest.java
DotDatasink wrote incorrect dotfiles:
- node/edge properties were written as graphviz properties (typically with no visual effect),
- vertices in multiple subgraphs were rendered only in the first subgraph
- individual GraphTransactions were not visible
- properties of graphheads, vertices, edges were not visible
> [#651] Render all Graphtransactions in Graphviz

- gradoop-flink/pom.xml
- gradoop-flink/src/test/java/org/gradoop/flink/model/GradoopFlinkTestBase.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/layouts/GraphCollectionLayoutFactoryTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/layouts/LogicalGraphLayoutFactoryTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/layouts/gve/GVEGraphCollectionLayoutFactoryTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/layouts/gve/GVEGraphLayoutFactoryTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/layouts/gve/GVELayoutTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/layouts/transactional/TxCollectionLayoutFactoryTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/layouts/transactional/TxCollectionLayoutTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/common/statistics/GraphStatisticsHDFSReaderTest.java
- gradoop-hbase/pom.xml
- gradoop-hbase/src/test/java/org/gradoop/GradoopHBaseTestBase.java
- gradoop-hbase/src/test/java/org/gradoop/HBaseTestSuite.java
- gradoop-hbase/src/test/java/org/gradoop/common/storage/impl/hbase/HBaseGraphStoreTest.java
- gradoop-hbase/src/test/java/org/gradoop/flink/io/impl/hbase/HBaseDataSinkSourceTest.java
- pom.xml
- updated flink and hbase dependencies to 1.3.1
- included flink-hadoop-compatibility and hbase-hadoop-compat dependency
- updated GradoopFlinkTestBase
- introduced HBaseTestSuite for all further gradoop-hbase tests
- force maven to run HBaseTestSuite
- added ignore annotation to GraphStatisticsHDFSReaderTest (link to issue #661)
- added license header to tests
> #524 update flink and hbase to 1.3.1

- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/Grouping.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/tuples/LabelGroup.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/grouping/GroupingTestBase.java
Fixed mixup, where the getter of the `LabelGroup` where defined wrong and the initialization of the `defaultLabelGroup` was mixed up. Also corrected tests.
> #665 LabelGroup mixup

- gradoop-examples/src/main/java/org/gradoop/examples/sna/SNABenchmark1.java
In the example SNA files provided in gradoop/gradoop-examples/src/main/resources/data/json/sna the label "Person" starts with a capital P. Using a small "p" in the getLabel().equals() predicate makes the example compile and run correctly, but the final result is empty. I suppose this was not the intended behaviour.
> Probable typo in SNA example yields empty result

- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/planning/planner/greedy/GreedyPlanner.java
* if a vertex/edge has a label predicate, the corresponding graph layout method will be called instead of loading all vertices/edges and applying a filter transformation
* ff used in combination with IndexedGVELayout, this avoids duplicating objects in a Flink dataflow caused by the filter transformation
* fixes #671
> [#671] Push label predicates down to graph layout

- gradoop-flink/src/main/java/org/gradoop/flink/algorithms/gelly/functions/EdgeToGellyEdgeWithDouble.java
- gradoop-flink/src/main/java/org/gradoop/flink/algorithms/gelly/shortestpaths/SingleSourceShortestPaths.java
- gradoop-flink/src/main/java/org/gradoop/flink/algorithms/gelly/shortestpaths/functions/SingleSourceShortestPathsAttribute.java
- gradoop-flink/src/main/java/org/gradoop/flink/algorithms/gelly/shortestpaths/functions/package-info.java
- gradoop-flink/src/main/java/org/gradoop/flink/algorithms/gelly/shortestpaths/package-info.java
- gradoop-flink/src/test/java/org/gradoop/flink/algorithms/gelly/shortestpaths/SingleSourceShortestPathsTest.java
Create an operator to wrap the gelly flink SingleSourceShortestPaths implementation. Added the new function EdgeToGellyEdgeWithDouble to cast incoming numeric values for edges to double to prepare the gelly algorithm. Tested the implementation with double and float input on equals by element data.
> [ #731] SingleSourceShortestPaths algorithm from Gelly Flink

- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/overlap/Overlap.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/overlap/OverlapTest.java
The new implementations computes the overlap by getting the intersection of both vertex and edge sets.
Edges are considered equal if their IDs are equal, their source, target ID and properties are ignored.
Added a new test case to check the new implementation by overlapping two graphs with equal vertex sets and disjoint edge sets.
fixes #786
> Fix overlap operator for two graphs overlapping by vertex set only.

- gradoop-common/src/main/java/org/gradoop/common/model/impl/properties/PropertyValue.java
- gradoop-common/src/test/java/org/gradoop/common/model/impl/properties/PropertyValueTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/properties/PropertiesSerializationTest.java
When writing a `PropertyValue` of a variable length where the size is larger than `Short.MAX_VALUE`, an `int` is used instead. In that case an additional bit-flag is set in the type byte. (`PropertyValue.FLAG_LARGE`)
Change test cases for larger properties to not expect an Exception.
Add test cases for serialization of larger properties.
Remove `validateBytesLength` method as the new maximum size is large enough to support any array. (The JVM does not support larger arrays.)
Some additional testing for larger Maps and BigDecimals may be necessary.
fixes #776
> Use an int to store the size of the internal representation of a large PropertyValue.

- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/functions/epgm/RenameLabelTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/functions/epgm/RenamePropertyKeysTest.java
Test the functionality of `RenameLabel` and  `RenamePropertyKey` for GraphHeads, Edges and Vertex.
fixed #780
> [#780] Add tests for RenameLabel and RenamePropertyKeys UDFs.

- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/aggregation/functions/containment/HasEdgeLabel.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/aggregation/functions/containment/HasVertexLabel.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/aggregation/functions/max/MaxEdgeProperty.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/aggregation/functions/max/MaxVertexProperty.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/aggregation/functions/min/MinEdgeProperty.java
Whilst working on the wiki page for the gradoop aggregate operator, i noticed some minor flaws in the code documentation.  
I propose this fixed version
* package: package org.gradoop.flink.model.impl.operators.aggregation.functions
> Fix JavaDoc of aggregation functions

- gradoop-flink/src/main/java/org/gradoop/flink/io/impl/csv/functions/ElementToCSV.java
- gradoop-flink/src/main/java/org/gradoop/flink/io/impl/csv/metadata/MetaDataParser.java
- gradoop-flink/src/main/java/org/gradoop/flink/io/impl/csv/metadata/PropertyMetaData.java
- gradoop-flink/src/test/java/org/gradoop/flink/io/impl/csv/CSVDataSinkTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/io/impl/csv/CSVTestBase.java
- gradoop-flink/src/test/java/org/gradoop/flink/io/impl/csv/indexed/IndexedCSVDataSinkTest.java
When a PropertyValue type does not match its metadata type, an empty string is written. Fixes #865
> [#865] Better handling of PropertyValues with non uniform types in CSVDataSink

- gradoop-examples/src/main/java/org/gradoop/examples/io/EdgeListExample.java
- gradoop-examples/src/main/java/org/gradoop/examples/patternmatching/CypherExample.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/LogicalGraph.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/LogicalGraphOperators.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/matching/single/cypher/CypherGraphConstructionTest.java
* remove unused method `match`
* Mark method `cypher` as deprecated
* Add new method `query` which is basically a re-named version of `cypher`
> [#874] Restructure pattern matching in LogicalGraph

- gradoop-flink/src/main/java/org/gradoop/flink/algorithms/gelly/pagerank/PageRank.java
- gradoop-flink/src/main/java/org/gradoop/flink/algorithms/gelly/pagerank/functions/PageRankResultKey.java
- gradoop-flink/src/test/java/org/gradoop/flink/algorithms/gelly/pagerank/PageRankTest.java
The wrapper for the PageRank Gelly algorithm was broken in recent Flink versions, because the result type was changed from a `Tuple` to an `UnaryResult`.
Added a new `KeySelector` to fix the implementation.
Added a test calling the operator and checking if the results were set as the correct property.
The `KeySelector` is basically the same as `org.gradoop.flink.algorithms.gelly.hits.functions.HitsResultKeySelector` and may be generalized to something like
```java
org.gradoop.flink.algorithms.gelly.functions.UnaryResultKey<T> extends KeySelector<UnaryResult<T>, T>
```
Should I do this (this would remove a duplicate) or leave it for now?
> [#947] Fix PageRank wrapper.

- gradoop-examples/src/main/java/org/gradoop/examples/biiig/FrequentLossPatterns.java
Replace an unsafe `exec` with a `ProcessBuilder`.
fixes #1030
> [#1030] Replace Runtime.exec with a ProcessBuilder

- pom.xml
Updated the version of the Maven Shade Plugin from 2.4.3 to 3.2.1. This enables Java 9+ support in the future and avoids some possible bugs that may occur.
> [#1105] Updated Maven Shade version.

- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/sampling/RandomVertexNeighborhoodSampling.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/sampling/functions/EdgeSourceVertexJoin.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/sampling/functions/EdgeTargetVertexJoin.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/sampling/functions/EdgesWithSampledVerticesFilter.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/sampling/functions/FilterVerticesWithDegreeOtherThanGiven.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/sampling/functions/VertexRandomMarkedMap.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/sampling/ParameterizedTestForGraphSampling.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/sampling/RandomVertexNeighborhoodSamplingTest.java
contains:
- bug fix
- simplify of `RandomVertexNeighborhoodSampling` Algorithm
- added test cases for empty vertex and edge sets
- clean up
fixes #1114
> [#1114] fixed bug in random vertex neighborhood sampling

- LICENSE
- gradoop-common/pom.xml
- gradoop-common/src/main/java/org/gradoop/common/model/impl/id/GradoopId.java
- gradoop-common/src/test/java/org/gradoop/common/model/impl/id/GradoopIdTest.java
- gradoop-examples/pom.xml
- gradoop-store/gradoop-accumulo/pom.xml
- pom.xml
Removed dependency to MongoDB ObjectId by reimplementing the functionality in GradoopId.
fixes #1125
> [#1125] Removed dependency to MongoDB ObjectId

- gradoop-store/gradoop-accumulo/src/main/java/org/gradoop/storage/impl/accumulo/AccumuloEPGMStore.java
- gradoop-store/gradoop-accumulo/src/main/java/org/gradoop/storage/impl/accumulo/io/AccumuloDataSink.java
- gradoop-store/gradoop-accumulo/src/test/java/org/gradoop/storage/impl/accumulo/AccumuloStoreTestBase.java
- gradoop-store/gradoop-accumulo/src/test/java/org/gradoop/storage/impl/accumulo/basic/StoreTest.java
Provides functions to drop and truncate tables on the accumulo store.
I had to add `IOException`s on the write functions, but those are declared on the `DataSink` interface anyway.
fixes #1160
> [#1160] Provide functions to drop and truncate tables for the Accumulo store.

- gradoop-flink/src/main/java/org/gradoop/flink/io/api/DataSource.java
- gradoop-flink/src/main/java/org/gradoop/flink/io/impl/csv/CSVDataSource.java
Switched to factory methods to avoid multiple graph heads to be created and stored on each element.
Further optimizations will be discussed in #1217 
fixes #974
> [#974] avoid multiple graph heads to be created using csv source

- gradoop-common/pom.xml
- gradoop-data-integration/pom.xml
- gradoop-examples/pom.xml
- gradoop-flink/pom.xml
- gradoop-store/gradoop-accumulo/pom.xml
- gradoop-store/gradoop-hbase/pom.xml
- gradoop-store/gradoop-store-api/pom.xml
- pom.xml
findbugs is replaced with spotbugs
fixes #1234 
Tested with Apache Maven *3.6.1* AND *3.3.9*
> [#1234] Updated versions of maven-plugins to support mvn 3.6

- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/sampling/PageRankSampling.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/sampling/PageRankSamplingTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/sampling/ParameterizedTestForGraphSampling.java
- Split the two test graphs into two different tests
- Pass old graph head to output graph (fixes `NullPointerException`, related: #1236 )
- Remove try/catch
- Use verify operator to create new edges
Fixes #1224
Fixes #1227
> [#1224, #1227] Fix NullPointerException

- pom.xml
> [#1256] Exclude mockito-all dependency from CAPF.

- gradoop-data-integration/src/main/java/org/gradoop/dataintegration/transformation/impl/PropertyTransformation.java
- gradoop-flink/src/main/java/org/gradoop/flink/io/impl/csv/CSVDataSink.java
- gradoop-flink/src/main/java/org/gradoop/flink/io/impl/gdl/GDLConsoleOutput.java
- gradoop-flink/src/main/java/org/gradoop/flink/io/impl/gdl/GDLEncoder.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/BaseGraph.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/BaseGraphCollectionFactory.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/BaseGraphFactory.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/epgm/GraphCollectionFactory.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/epgm/LogicalGraph.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/epgm/LogicalGraphFactory.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/aggregation/Aggregation.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/Grouping.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/GroupingGroupCombine.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/grouping/GroupingGroupReduce.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/subgraph/Subgraph.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/transformation/ApplyTransformation.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/transformation/Transformation.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/verify/Verify.java
- gradoop-flink/src/main/java/org/gradoop/flink/util/GradoopFlinkConfig.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/grouping/GroupingTestBase.java
#1298 
- GDL output is now working on BaseGraph and BaseGraphCollection
- fixes #1298 
#1299
- Added GC Type to BaseGraph
- Added `getCollectionFactory` to BaseGraph
- fixes #1299
> [#1298][#1299]  Added GC Type to BaseGraph and generified GDL print method   

- gradoop-common/src/main/java/org/gradoop/common/model/impl/properties/PropertyValue.java
- gradoop-common/src/main/java/org/gradoop/common/model/impl/properties/strategies/NullStrategy.java
- gradoop-common/src/main/java/org/gradoop/common/model/impl/properties/strategies/PropertyValueStrategyFactory.java
- gradoop-common/src/test/java/org/gradoop/common/model/impl/properties/PropertyValueTest.java
Still no comparison between most types.
Partly fixes #1314
> [#1314] Fix compare to for NULL_VALUE

- gradoop-temporal/src/main/java/org/gradoop/temporal/model/impl/TemporalGraph.java
- gradoop-temporal/src/main/java/org/gradoop/temporal/model/impl/TemporalGraphCollection.java
- gradoop-temporal/src/test/resources/log4j-test.properties
added print operator to TemporalGraph and TemporalGraphCollection 
+ also added a missing log4j config in gradoop-temporal tests
> [#1111] added print operator to TemporalGraph and TemporalGCollection

- gradoop-common/pom.xml
- gradoop-store/gradoop-hbase/pom.xml
- pom.xml
Replaces this `hbase-server` runtime-dependency with `hbase-common` and `hbase-client` (for `gradoop-hbase`)
This removes many transitive dependencies.
fixes #1386
> [#1386] Replace hbase-server dependency.

- gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/BaseGraph.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/BaseGraphCollection.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/BaseGraphCollectionOperators.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/BaseGraphOperators.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/GraphCollectionOperators.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/LogicalGraphOperators.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/epgm/GraphCollection.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/epgm/LogicalGraph.java
- gradoop-temporal/src/main/java/org/gradoop/temporal/model/api/TemporalGraphOperators.java
- gradoop-temporal/src/main/java/org/gradoop/temporal/model/impl/TemporalGraph.java
- gradoop-temporal/src/main/java/org/gradoop/temporal/model/impl/TemporalGraphCollection.java
Move `query` and `isEmpty` from `LogicalGraph/GraphCollection` and `TemporalGraph(Collection)` to `BaseGraph(Collection)`.
Fixes #1366
> [#1366] Move generified operators to BaseGraphOperators.

- gradoop-flink/src/main/java/org/gradoop/flink/io/api/metadata/MetaDataSource.java
> [#1439] Generify tuplesFromGraph

- gradoop-checkstyle/pom.xml
- gradoop-common/pom.xml
- gradoop-data-integration/pom.xml
- gradoop-examples/gradoop-examples-operators/pom.xml
- gradoop-examples/gradoop-examples-temporal/pom.xml
- gradoop-flink/pom.xml
- gradoop-store/gradoop-accumulo/pom.xml
- gradoop-store/gradoop-hbase/pom.xml
- gradoop-store/gradoop-store-api/pom.xml
- gradoop-temporal/pom.xml
- pom.xml
This removes some unused or duplicate configuration from the build config.
#1417 Cleanup build config
Our build config seems very bloated. While most parts are necessary, some are or have become unnecessary. This change removes some of that, namely the `snapshot` profile, which was identical to the `release` profile. This also removes the `release` plugin which is currently not used in our release process and some redundant config of the `surefire` plugin.
A full build has been tested with the new changes. 
A release has to be tested.
> [#1417] Remove some unused config in poms.

- gradoop-flink/src/main/java/org/gradoop/flink/io/impl/dot/DOTDataSink.java
* Changed the default background color of the DOTDataSink class to "#000000", x11 code for black
* Now it should be accepted by GraphViz
> [#1458] DotDataSink Background Color

- gradoop-common/src/main/java/org/gradoop/common/model/impl/id/GradoopId.java
- gradoop-common/src/test/java/org/gradoop/common/model/impl/id/GradoopIdTest.java
Fixes the implementation of methods from `CopyableValue` in `GradoopId` and adds tests.
Fixes the broken `copy` and `copyTo` methods and adds tests verifying that the copy is equal but the references are not the same.
#1468 
This leads to some weird issues when Flink decides to reuse `GradoopId` objects, even with object reuse disabled.
This adds new tests, this has not been tested before (see coverage reports).
> [#1468] Fix CopyableValue implementation in GradoopId

- gradoop-temporal/src/main/java/org/gradoop/temporal/util/TimeFormatConversion.java
- gradoop-temporal/src/test/java/org/gradoop/temporal/util/TimeFormatConversionTest.java
A new function is added to convert a timestamp represented as milliseconds from epoch to a LocalDateTime object.
The function consumes a long timestamp and converts it to a LocalDateTime object.
A helper function to easily convert timestamps e.g. for using the snapshot operator etc.
Test function added.
> [#1471] Added toLocalDateTime function to class TimeFormatConversion

- gradoop-quickstart/pom.xml
Use -DskipITs to skip maven archetype integration-test
Use -DskipITs to skip maven archetype integration-test. -DskipITs is used in the maven-failsafe-plugin to skip integration tests.
Fixes #1463
#1463
Running it with -DskipITs
> [#1463] Use -DskipITs to skip maven archetype integration-test

- gradoop-common/src/main/java/org/gradoop/common/model/impl/properties/PropertyValueUtils.java
- gradoop-common/src/test/java/org/gradoop/common/model/impl/properties/PropertyValueUtilsTest.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/aggregation/functions/max/Max.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/aggregation/functions/min/Min.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/aggregation/functions/max/MaxTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/aggregation/functions/min/MinTest.java
- pom.xml
Extended min and max aggregation with date and datetime support
#1496
Atm, just numerical types PropertyValue types can be used in min/max aggregations. It's not possible to use date or datetime types
Several JUnit and testNG classes with coverage.
> [#1496] Extended min and max aggregation with date and datetime types

- gradoop-flink/src/main/java/org/gradoop/flink/io/impl/csv/CSVBase.java
- gradoop-flink/src/main/java/org/gradoop/flink/io/impl/csv/indexed/IndexedCSVDataSink.java
- gradoop-flink/src/main/java/org/gradoop/flink/io/impl/csv/indexed/IndexedCSVDataSource.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/api/epgm/BaseGraphFactory.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/api/layouts/LogicalGraphLayoutFactory.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/epgm/LogicalGraphFactory.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/layouts/gve/GVEGraphLayoutFactory.java
- gradoop-flink/src/main/java/org/gradoop/flink/model/impl/layouts/gve/indexed/IndexedGVELayout.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/layouts/gve/BaseGVELayoutTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/layouts/gve/GVELayoutTest.java
- gradoop-flink/src/test/java/org/gradoop/flink/model/impl/layouts/gve/indexed/IndexedGVELayoutTest.java
- gradoop-temporal/src/main/java/org/gradoop/temporal/io/impl/csv/indexed/TemporalIndexedCSVDataSink.java
- gradoop-temporal/src/main/java/org/gradoop/temporal/io/impl/csv/indexed/TemporalIndexedCSVDataSource.java
- gradoop-temporal/src/main/java/org/gradoop/temporal/io/impl/csv/indexed/package-info.java
- gradoop-temporal/src/main/java/org/gradoop/temporal/model/impl/TemporalGraphCollectionFactory.java
- gradoop-temporal/src/main/java/org/gradoop/temporal/model/impl/TemporalGraphFactory.java
- gradoop-temporal/src/main/java/org/gradoop/temporal/model/impl/layout/TemporalGraphCollectionLayoutFactory.java
- gradoop-temporal/src/main/java/org/gradoop/temporal/model/impl/layout/TemporalGraphLayoutFactory.java
- gradoop-temporal/src/main/java/org/gradoop/temporal/model/impl/layout/TemporalIndexedLayout.java
- gradoop-temporal/src/test/java/org/gradoop/temporal/io/impl/csv/indexed/TemporalIndexedCSVDataSinkTest.java
- gradoop-temporal/src/test/java/org/gradoop/temporal/io/impl/csv/indexed/TemporalIndexedCSVDataSourceTest.java
- gradoop-temporal/src/test/java/org/gradoop/temporal/model/impl/layout/BaseTemporalGVELayoutTest.java
- gradoop-temporal/src/test/java/org/gradoop/temporal/model/impl/layout/TemporalGVELayoutTest.java
- gradoop-temporal/src/test/java/org/gradoop/temporal/model/impl/layout/TemporalIndexedLayoutTest.java
I added an indexed source and sink for temporal graphs and collections. I also added a TemporalIndexedLayout that is automatically used as a layout, if the function "fromIndexedDatasets" are used in the layout factories.
#1510 
It is used as an alternative graph layout and will be used to test the performance improvements on operators like pattern matching.
Unit and integration tests.
> [#1510] Add indexed temporal csv source and sink

- gradoop-data-integration/src/main/java/org/gradoop/dataintegration/importer/impl/csv/MinimalCSVImporter.java
- gradoop-data-integration/src/main/java/org/gradoop/dataintegration/importer/impl/csv/functions/CsvRowToProperties.java
- gradoop-data-integration/src/test/java/org/gradoop/dataintegration/importer/impl/csv/MinimalCSVImporterTest.java
- gradoop-data-integration/src/test/resources/csv/expectedQuoted.gdl
- gradoop-data-integration/src/test/resources/csv/inputQuoted.csv
Add parseQuotedStrings flag to MinimalCSVImporter. Replace readFile with Flink CSVReader to use the flag.
Fixes #1481 
Quoting is popular in CSV files to escape delimiters.
New test added.
> [#1481] Add support for quoted csv fields in MinimalCSVImporter
